spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    generate-ddl: true
    database: mysql
  profiles:
    active: test
    default: aws

logging:
  level:
    org.hibernate.SQL: debug


server:
  servlet:
    session:
      timeout: 30m # 세션 타임아웃 30분
