name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: spring-boot-app
          path: build/libs/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: spring-boot-app

      - name: Save SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$EC2_KEY" > ~/.ssh/private-key.pem
          chmod 600 ~/private-key.pem  # pem 키에 적절한 권한 부여
          eval $(ssh-agent -s)

      - name: Add EC2 public key to known hosts
        run: |
          ssh-keygen -y -f ~/.ssh/private-key.pem >> ~/.ssh/known_hosts

      - name: Copy JAR file to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          cd ${{ github.workspace }}
          scp -i ~/.ssh/private-key.pem -o StrictHostKeyChecking=no *.jar $EC2_USER@$EC2_HOST:/home/ubuntu/app.jar
    

      - name: Deploy on EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          ssh -i ~/.ssh/private-key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
            docker stop springboot_app || true && docker rm springboot_app || true
            docker run -d --name springboot_app -p 8080:8080 -v /home/ubuntu/app.jar:/app/app.jar openjdk:17 
          export DB_URL=${DB_URL}
            export DB_USERNAME=${DB_USERNAME}
            export DB_PASSWORD=${DB_PASSWORD}
          java -jar /app/app.jar
          EOF
